/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ego2gtyk4fdqni5xhpyk6nnxha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rgryroqgsbd5pkgegqhwh2vf7u",
    "aws_cognito_identity_pool_id": "us-east-1:291a7e22-e522-4645-9662-c7db63d4a87e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZnvZyq1h3",
    "aws_user_pools_web_client_id": "1hm4e48pjvt6ks2cj1h9b8mf6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "escapeoutbucket213334-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
