/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://z4mwfd452nhxnnacf6m3nmm22y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ubxjbxuv6zcwbdr366tbusjt7a",
    "aws_cognito_identity_pool_id": "us-east-1:467dbd9f-c778-46a2-8478-49ada36194d6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ys31U1J1l",
    "aws_user_pools_web_client_id": "1qm22p6e2fblfafjei9nsifa1g",
    "oauth": {
        "domain": "dnsjt0ciamhb-perri.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://dev.play.escapeout.games/",
        "redirectSignOut": "http://localhost:3000/,https://dev.play.escapeout.games/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "escapeoutbucket213334-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
